import Head from "next/head";
import LandingPage from "../pages/home";
import Navbar from "../components/Navbar";

import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Layout from "../components/Layout";
import Header from "../components/Header";
import FreshFood from "@/components/FreshFood";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Layout>
				<Head>
					<title>Betachops</title>
					{/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
				</Head>
				<Header />
				<FreshFood />
			</Layout>
		</>
	);
}
