import Head from "next/head";
// import App from "./_app";

import Layout from "../components/Layout";
import LandingPage from "./home";
// import Header from "../components/Header";
// import Categories from "../components/Categories";
// import WhyUs from "@/components/WhyUs";
// import Footer from "@/components/Footer";

export default function Home() {
	return (
		<div className="">
			<Head>
				<title>Betachops</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>
				<LandingPage />
			</Layout>
		</div>
	);
}
